# Generated by Django 5.2.3 on 2025-06-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servermanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minecraftserver',
            name='container_id',
        ),
        migrations.RemoveField(
            model_name='minecraftserver',
            name='user_id',
        ),
        migrations.AddField(
            model_name='minecraftserver',
            name='cpu_cores',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='minecraftserver',
            name='name',
            field=models.CharField(default='default_name'),
        ),
        migrations.AlterField(
            model_name='minecraftserver',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='minecraftserver',
            name='port',
            field=models.IntegerField(unique=True),
        ),
    ]
