# Generated by Django 5.2.3 on 2025-06-25 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servermanager', '0002_remove_minecraftserver_container_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='minecraftserver',
            name='container_id',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='minecraftserver',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='minecraftserver',
            name='name',
            field=models.CharField(default='default_name', max_length=100),
        ),
    ]
