# Generated by Django 5.2.3 on 2025-06-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servermanager', '0003_minecraftserver_container_id_minecraftserver_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='minecraftserver',
            name='mem_limit',
            field=models.CharField(default='2g', max_length=10),
        ),
    ]
