# Generated by Django 5.2.3 on 2025-06-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servermanager', '0005_alter_minecraftserver_cpu_cores'),
    ]

    operations = [
        migrations.AddField(
            model_name='minecraftserver',
            name='custom_world',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='minecraftserver',
            name='mods',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='minecraftserver',
            name='server_type',
            field=models.CharField(choices=[('java', 'Java Edition'), ('bedrock', 'Bedrock Edition')], default='java', max_length=10),
        ),
        migrations.AddField(
            model_name='minecraftserver',
            name='whitelist',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
