# Generated by Django 5.2.3 on 2025-06-30 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servermanager', '0006_minecraftserver_custom_world_minecraftserver_mods_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minecraftserver',
            name='custom_world',
        ),
        migrations.RemoveField(
            model_name='minecraftserver',
            name='name',
        ),
        migrations.RemoveField(
            model_name='minecraftserver',
            name='whitelist',
        ),
        migrations.AddField(
            model_name='minecraftserver',
            name='world_data_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ワールドデータパス'),
        ),
        migrations.AlterField(
            model_name='minecraftserver',
            name='container_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='minecraftserver',
            name='cpu_cores',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='minecraftserver',
            name='mods',
            field=models.TextField(blank=True, default='', help_text='CurseForgeのFile IDをカンマ区切りで入力してください。', verbose_name='導入MOD (CurseForge File IDs)'),
        ),
        migrations.AlterField(
            model_name='minecraftserver',
            name='server_type',
            field=models.CharField(choices=[('java', 'Java Edition'), ('be', 'Bedrock Edition')], default='java', max_length=10, verbose_name='サーバーエディション'),
        ),
        migrations.AlterField(
            model_name='minecraftserver',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
