# Generated by Django 5.2.3 on 2025-06-30 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servermanager', '0007_remove_minecraftserver_custom_world_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='minecraftserver',
            name='version',
            field=models.CharField(default='LATEST', max_length=20, verbose_name='サーバーバージョン'),
        ),
        migrations.AlterField(
            model_name='minecraftserver',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
