# Generated by Django 5.2.3 on 2025-07-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servermanager', '0009_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minecraftserver',
            name='server_type',
        ),
        migrations.AddField(
            model_name='minecraftserver',
            name='backup_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='バックアップタイプ'),
        ),
        migrations.AddField(
            model_name='minecraftserver',
            name='plan_type',
            field=models.CharField(choices=[('java', 'Java Edition'), ('be', 'Bedrock Edition'), ('web', 'Web Hosting')], default='web', max_length=10, verbose_name='プランタイプ'),
        ),
        migrations.AddField(
            model_name='minecraftserver',
            name='storage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ディスク容量'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
