# Generated by Django 5.2.3 on 2025-06-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MinecraftServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('container_id', models.CharField(max_length=64)),
                ('port', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
