# Generated by Django 5.2.3 on 2025-06-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servermanager', '0004_minecraftserver_mem_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minecraftserver',
            name='cpu_cores',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
